### PR TITLE
Added functionality to get an enum variant from it's corresponding index

### PR DESCRIPTION
**Pull request by ozeidan**
I wanted to be able to convert 'enum variant -> index' and 'index -> enum variant' like it is possible in other languages. I found your trait but it didn't implement the 'index -> enum variant' direction so I completed it. This is my first contribution to another project so please correct my mistakes if you find any.

### CODE REVIEW

**Comment by regresscheck** [comment]
Hi, thank you for pull request! 
I'd have merged it, but just want to ask. Wouldn't it be more convenient to have only enum_index_derive with both derives? So the user of the library doesn't need to write two #[macro_use] and externs.

**Comment by ozeidan** [comment]
The problem is that the derive that I wrote only works for C-like enums but the EnumIndex derive works for enums with any kind of variants. So I figured I should seperate them. Do you have a better suggestion? Maybe we could conver the indexes to variants of any kind by  filling them with default values (https://doc.rust-lang.org/std/default/trait.Default.html).

**Comment by regresscheck** [comment]
I just not sure about an idea of splitting one library on multiple crates. I was forced to create second (enum_index_derive) because it's the only way to use proc macro, in parallel universe I'd leave it in one crate. Talking about index_enum, the requirement of C-like enums will not dissappear with new crate :) Can you please move code into the same crate? 

Default:
Yeah, that's what I was thinking about. It's easy to fill each parameter of variant with default value. I'll  implement it after merge

**Comment by ozeidan** [comment]
Hey, I moved the implementation into the enum_index_derive crate, is it fine like this?

**Comment by regresscheck** [comment]
Thank you very much! I'll also make implementation for Default pretty soon and update version on crates.io

**Pull request merged**
